FROM debian:stretch

ARG BUNDLE_DIR

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y apt-utils ca-certificates wget curl

# Install KubeSeal
RUN wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.10.0/kubeseal-linux-amd64 -O kubeseal
RUN install -m 755 kubeseal /usr/local/bin/kubeseal

# Install Helm 3
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
RUN chmod 700 get_helm.sh
RUN ./get_helm.sh

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR
