apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: prom-operator-network-policy
  namespace: monitoring
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    protocol: TCP
  egress:
  - action: Allow
    protocol: TCP
