---
# Source: azuremonitor-containers/templates/omsagent-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: omsagent-secret
  namespace: kube-system
  labels:
    chart: azuremonitor-containers-2.5.0
    release: omsagent
    heritage: Helm
type: Opaque
data:
  WSID: "ZGEwMTQzNmMtNTU3Mi00ZjA1LTlhZmEtNGU5YTM0MTNmMTY2"
  KEY: "Y3c3NXNhM25iYjBOU1RhQW5YOVdOT1NldjUvamdyS0NCQkJUcjZ0RlBROW9SK2doL2FLMmxWdkRrV0lzWEs3UWc2Z0JPMmdNS1dtcnBWZU9lTlhzOFE9PQ=="
  DOMAIN: "b3BpbnNpZ2h0cy5henVyZS5jb20="
