---
# Source: azuremonitor-containers/templates/omsagent-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: omsagent
 namespace: kube-system
 labels:
   chart: azuremonitor-containers-2.5.0
   release: omsagent
   heritage: Helm
spec:
 selector:
   matchLabels:
     dsName: "omsagent-ds"
 updateStrategy:
  type: RollingUpdate
 template:
  metadata:
   labels:
    dsName: "omsagent-ds"
   annotations:
    agentVersion: ciprod11012019
    dockerProviderVersion: 7.0.0-6
    schema-versions: "v1"
  spec:
   serviceAccountName: omsagent
   containers:
     - name: omsagent
       image: "mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod11012019"
       imagePullPolicy: IfNotPresent
       resources:
         limits:
           cpu: 150m
           memory: 600Mi
         requests:
           cpu: 75m
           memory: 225Mi
       env:
       - name: ACS_RESOURCE_NAME
         value: "DemoLocalCluster"
       - name: CONTROLLER_TYPE
         value: "DaemonSet"
       - name: NODE_IP
         valueFrom:
            fieldRef:
              fieldPath: status.hostIP
       securityContext:
         privileged: true
       ports:
       - containerPort: 25225
         protocol: TCP
       - containerPort: 25224
         protocol: UDP
       volumeMounts:
        - mountPath: /hostfs
          name: host-root
          readOnly: true
        - mountPath: /var/run/host
          name: docker-sock
        - mountPath: /var/log
          name: host-log
        - mountPath: /var/lib/docker/containers
          name: containerlog-path
        - mountPath: /etc/kubernetes/host
          name: azure-json-path
        - mountPath: /etc/omsagent-secret
          name: omsagent-secret
          readOnly: true
        - mountPath: /etc/config/settings
          name: settings-vol-config
          readOnly: true
       livenessProbe:
        exec:
         command:
         - /bin/bash
         - -c
         - "/opt/livenessprobe.sh"
        initialDelaySeconds: 60
        periodSeconds: 60
   nodeSelector:
    beta.kubernetes.io/os: linux
   # Tolerate below taints on nodes of k8s clusters to schedule ds pod.
   tolerations:
     - operator: "Exists"
       effect: "NoSchedule"
     - operator: "Exists"
       effect: "NoExecute"
     - operator: "Exists"
       effect: "PreferNoSchedule"
   volumes:
    - name: host-root
      hostPath:
       path: /
    - name: docker-sock
      hostPath:
       path: /var/run
    - name: container-hostname
      hostPath:
       path: /etc/hostname
    - name: host-log
      hostPath:
       path: /var/log
    - name: containerlog-path
      hostPath:
       path: /var/lib/docker/containers
    - name: azure-json-path
      hostPath:
       path: /etc/kubernetes
    - name: omsagent-secret
      secret:
       secretName: omsagent-secret
    - name: settings-vol-config
      configMap:
        name: container-azm-ms-agentconfig
        optional: true
