apiVersion: v1
kind: Namespace
metadata:
  name: flighttracker-dev
  labels:
    app: flighttracker-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: dummy-ns
  labels:
    app: dummy-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: flighttracker-production
  labels:
    app: flighttracker-production
---
apiVersion: v1
kind: Namespace
metadata:
  name: flighttracker-staging
  labels:
    app: flighttracker-staging
