apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helmtest
  namespace: default
spec:
  releaseName: helmtest
  targetNamespace: default
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    repository: https://griffith.azurecr.io/helm/v1/repo
    name: hello-world
    version: 0.1.0
