apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prom
  namespace: default
spec:
  releaseName: prometheus-operator
  targetNamespace: kured
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 3.3.6
  values:
    replicas: 1