apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: dummy-ns
  labels:
    app: dummy-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    app: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    app: staging
